services:
  drinkbot:
    build: .
    container_name: drinkbot

    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}

    restart: unless-stopped

    volumes:
      - drinkbot-data:/data

    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "3"

volumes:
  drinkbot-data: